#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: 2659038
#
# Source0 file verified with key 0x528897B826403ADA
#
Name     : pinentry
Version  : 1.3.1
Release  : 34
URL      : https://gnupg.org/ftp/gcrypt/pinentry/pinentry-1.3.1.tar.bz2
Source0  : https://gnupg.org/ftp/gcrypt/pinentry/pinentry-1.3.1.tar.bz2
Source1  : https://gnupg.org/ftp/gcrypt/pinentry/pinentry-1.3.1.tar.bz2.sig
Source2  : 528897B826403ADA.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: pinentry-bin = %{version}-%{release}
Requires: pinentry-data = %{version}-%{release}
Requires: pinentry-info = %{version}-%{release}
Requires: pinentry-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : fltk-dev
BuildRequires : gcr-dev
BuildRequires : gnupg
BuildRequires : gtk3-dev
BuildRequires : libassuan-dev
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libgpg-error-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(KF6GuiAddons)
BuildRequires : pkgconfig(KF6WindowSystem)
BuildRequires : pkgconfig(gcr-4)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(x11)
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-add-pinentry-wrapper.patch

%description
PINEntry
---------
This is a collection of PIN or passphrase entry dialogs which
utilize the Assuan protocol as specified in the Libassuan manual.

%package bin
Summary: bin components for the pinentry package.
Group: Binaries
Requires: pinentry-data = %{version}-%{release}
Requires: pinentry-license = %{version}-%{release}

%description bin
bin components for the pinentry package.


%package data
Summary: data components for the pinentry package.
Group: Data

%description data
data components for the pinentry package.


%package extras
Summary: extras components for the pinentry package.
Group: Default

%description extras
extras components for the pinentry package.


%package info
Summary: info components for the pinentry package.
Group: Default

%description info
info components for the pinentry package.


%package license
Summary: license components for the pinentry package.
Group: Default

%description license
license components for the pinentry package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 528897B826403ADA' gpg.status
%setup -q -n pinentry-1.3.1
cd %{_builddir}/pinentry-1.3.1
%patch -P 1 -p1
pushd ..
cp -a pinentry-1.3.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720103588
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-pinentry-gtk2 \
--disable-pinentry-qt5 \
--enable-pinentry-gnome3 \
--enable-pinentry-curses
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-pinentry-gtk2 \
--disable-pinentry-qt5 \
--enable-pinentry-gnome3 \
--enable-pinentry-curses
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720103588
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pinentry
cp %{_builddir}/pinentry-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pinentry/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## install_append content
install -m 0755 pinentry-wrapper %{buildroot}/usr/bin/pinentry
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/pinentry-curses
/V3/usr/bin/pinentry-qt
/usr/bin/pinentry
/usr/bin/pinentry-curses
/usr/bin/pinentry-qt

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnupg.pinentry-qt.desktop
/usr/share/pixmaps/pinentry.png

%files extras
%defattr(-,root,root,-)
/V3/usr/bin/pinentry-fltk
/V3/usr/bin/pinentry-gnome3
/usr/bin/pinentry-fltk
/usr/bin/pinentry-gnome3

%files info
%defattr(0644,root,root,0755)
/usr/share/info/pinentry.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pinentry/4cc77b90af91e615a64ae04893fdffa7939db84c
